# NumPy Tutorial



[Python](https://www.python.org) is highly encouraged for EE 454.
And for the purpose of this class, we will use it to create a power flow solver using the Newton Raphson method. 
[NumPy](https://www.numpy.org) and [SciPy](https://www.scipy.org) are the packages that heavily used in this end.

In this tutorial, we will go through some simple examples that demonstrate how to use NumPy on basic linear algebra calculations.



## Other Resources

Due to the length of this tutorial, we will not be able to cover all aspects of Python.
Fortunately, as one of the most popular programming languages, there are a lot of resources for learning Python.

Here we provide a list of the tutorials, in case you are interested.

* [Python For Beginners](https://www.python.org/about/gettingstarted/)
* [The Python Tutorial](https://docs.python.org/3/tutorial/)
* [NumPy User Guide](https://docs.scipy.org/doc/numpy-1.15.4/user/)
* [NumPy Quickstart Tutorial](https://docs.scipy.org/doc/numpy-1.15.4/user/quickstart.html)
* [SciPy Tutorial](https://docs.scipy.org/doc/scipy-1.2.0/reference/tutorial/)

Major content of this tutorial is extracted from these sites.

In [15]:
# install missing dependences 
!pip install xlsxwriter

     |████████████████████████████████| 143kB 2.7MB/s 


In [0]:
# ways to import packages and modules

import scipy
import numpy as np
from numpy import random
import xlsxwriter


In [0]:
# indentation

a = 1

for i in range(5):
  print(i)
 print(i**2)


IndentationError: ignored

In [0]:
# logical operators

a = True
b = False

c = 1
d = 2

if c == 1 and a: # a or b; not a and b; etc
  print(a)

In [0]:
# basic operations of string

a = 'Hello '
b = 'world!'


astring = a + b

print(astring)
print(len(astring))
print(astring.index('o'))
print(astring.count("l"))
print(astring[3:7])
print(astring.upper())
print(astring.lower())

print(astring.startswith("Hello"))
print(astring.endswith("asdfasdfasdf"))

words = astring.split()
print(words)
print(' '.join(words))

Hello world!
12
4
3
lo w
HELLO WORLD!
hello world!
True
False
['Hello', 'world!']
Hello world!


In [3]:
# basic operations of list

# empty list
my_list = []

# list of integers
my_list = [1, 2, 3]

# list with mixed datatypes
my_list = [1, "Hello", 3.4]


# nested list
my_list = ["mouse", [8, 4, 6], ['a']]

print(my_list[0])
print(my_list[-1])


my_list = ['a','b','c','d','e','f','g','h','i']
print(my_list[:-5])

my_list_1 = ['cat', 'dog']
my_list_2 = ['bird', 'mouse']
my_list_1.append('horse')
print(my_list_1)


my_list_all = my_list_1 + my_list_2
print(my_list_all)
print(my_list_1*3)

my_list.reverse()
print(my_list)

numbers = [x for x in range(10)]
print(numbers)

print('p' in my_list)

mouse
['a']
['a', 'b', 'c', 'd']
['cat', 'dog', 'horse']
['cat', 'dog', 'horse', 'bird', 'mouse']
['cat', 'dog', 'horse', 'cat', 'dog', 'horse', 'cat', 'dog', 'horse']
['i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
False


In [7]:
# for loops and enumerated lists
list1 = ['a','b','c','d','e','f']
list2 = [10, 20, 50, 30, 80, 40]

for i in list1:
    print(i)

    
#access items in correlated lists
for (i, x) in enumerate(list1):
    res = [x, list2[i]]
    print(res)

#access items in correlated lists
for (x1, x2) in zip(list1, list2):
    print([x2,x1])

a
b
c
d
e
f
['a', 10]
['b', 20]
['c', 50]
['d', 30]
['e', 80]
['f', 40]
[10, 'a']
[20, 'b']
[50, 'c']
[30, 'd']
[80, 'e']
[40, 'f']


In [8]:
# basic operations of dict

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

print(len(thisdict))



{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
3


In [9]:
# 2nd cell of dict

x = thisdict["model"]

del thisdict["model"]

for x in thisdict:
  print(x, thisdict[x])
  
print("model" in thisdict)

brand Ford
year 1964
False


In [0]:
# intro to numpy
# advantages of numpy over list: convenient, fast, memory efficient

import numpy as np


# from list
a = np.array([1, 2, 3])
print(a.shape)
print(a.dtype)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]], dtype=np.int64)
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])



(3,)
int64
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [0]:
# create array

a = np.zeros((2,2))
print(a) 

b = np.ones((1,2))
print(b)

c = np.full((2,2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2,2))
print(e)
  

# other operations

a = np.arange(1,5, 2)
a.reshape(2,1)
print(a)
bool_idx = (a > 2)
print(bool_idx)
 

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.33983648 0.48478324]
 [0.58380519 0.11434571]]
[1 3]
[False  True]


In [0]:
# slicing, value changing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]


print(a[0, 1])

b[0, 0] = 77

print(a[0, 1])


In [20]:
# Complex Numbers using Numpy 

Z = 5 + 3j 
network = np.array([[1+2j, 2+1j],\
                   [3+1j, 2+4j]])

print(Z)
print(Z.real)
print(network)
print(network.imag)


(5+3j)
5.0
[[1.+2.j 2.+1.j]
 [3.+1.j 2.+4.j]]
[[2. 1.]
 [1. 4.]]


In [0]:
# math operations; check your linear algebra operators

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(x * 3)
print(np.sqrt(x))


v = np.array([9,10])
w = np.array([11, 12])

print(x+v)
#
## Inner product of vectors
print(v.dot(w))
#
print(x.dot(v))
#
print(x.dot(y))
#
print(x.T)
#
print(x.mean())
print(x.var())
print(x.std())
print(x.sum(axis=1))
#
##np.loadtxt('filename.txt')


[[ 6.  8.]
 [10. 12.]]
[[ 3.  6.]
 [ 9. 12.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[10. 12.]
 [12. 14.]]
219
[29. 67.]
[[19. 22.]
 [43. 50.]]
[[1. 3.]
 [2. 4.]]
2.5
1.25
1.118033988749895
[3. 7.]


In [0]:
# linalg

from scipy import linalg
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
linalg.inv(A)

linalg.det(A)

In [31]:
# Copies and views can super easily be the source of bug
x = np.zeros(5)
y = x
y[0] = 1.0
print('x = ', x)
print('y = ', y)

x =  [1. 0. 0. 0. 0.]
y =  [1. 0. 0. 0. 0.]


In [33]:
x = np.zeros(5)
y = x.copy()
y[0] = 1.0
print('x = ', x)
print('y = ', y)

x =  [0. 0. 0. 0. 0.]
y =  [1. 0. 0. 0. 0.]


In [34]:
# slicing is a view
X = np.zeros((2,3))
x0 = X[:,0]
x0[:] = 1.0
print('X = ', X)

X =  [[1. 0. 0.]
 [1. 0. 0.]]


In [0]:
# Reading Data from Excel
import openpyxl 

file = "input.xlsx"

wb = openpyxl.load_workbook(file, data_only=True)

sheet = wb['BusData']

In [0]:
# Writing arrays to output files
# This is one example, many Python libraries achieve the same result

N = 5 
mydata = np.ones((N,N))

filepath = "output.xlsx"

workbook = xlsxwriter.Workbook(filepath)
worksheet = workbook.add_worksheet()

row = 0

for col, data in enumerate(mydata):
    worksheet.write_column(row, col, data)

workbook.close()

In [23]:
# define functions

def myfunc(name):
  print("Hello, my name is " + name)

def doCalc(in1, in2):
  res = in1 + in2
  return res

myfunc('Jackie')

output = doCalc(4, 7)
out2 = doCalc(Z,network[1,1])

print(out2)

Hello, my name is Jackie
(7+7j)


In [24]:
# define class

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello, my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()

Hello, my name is John


Below are additional Python sample functions for reference

In [10]:
# python doesn't throw out error until it runs the line

name= 'Jackie'

if name is 'Jackie':
  print('hi '+name)
else:
  whatever()

hi Jackie


In [0]:
# intro to matplotlib
# https://matplotlib.org/tutorials/index.html

import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

In [0]:
# intro to scipy
# https://docs.scipy.org/doc/scipy/reference/tutorial/index.html

import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
d = squareform(pdist(x, 'euclidean'))
print(d)


In [0]:
# integrate

import scipy.integrate as integrate

result = integrate.quad(lambda x: x**2, 0, 1)
print(result[0])


integrate.quad(lambda x: yourfunc(x), 0, np.inf)


In [0]:
# file I/O

fname = 'file.txt'

with open(fname, 'w') as fin:
  for i in range(10):
    fin.write(str(i)+'\n')
    
with open(fname) as fin:
  for line in fin:
    print(line.strip())

0
1
2
3
4
5
6
7
8
9


In [0]:
# package for file, directory read

import os